chromadb:
  path: ./chromadb
  collection: all_documents
  dim: 1024
  n_results: 15

text:
  chunk_text_size: 500
  chunk_text_overlap: 50

reranking:
  enabled: true # enable reranker using CrossEncoder
  model: "cross-encoder/ms-marco-MiniLM-L-6-v2"

embedding:
  model: "mixedbread-ai/mxbai-embed-large-v1"
  trust_remote_code: false

ollama:
  api_url: "http://localhost:11434"
  model: "llama3.1"
